site_name: Starlite
repo_url: https://github.com/Goldziher/starlite
repo_name: Goldziher/starlite
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  favicon: images/favicon.ico
  logo: images/starlite-icon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
  plugins:
    - search
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/X3FJqy8d2j
    - icon: fontawesome/brands/github
      link: https://github.com/Goldziher/starlite
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
