name: publish
on:
  release:
    types: [published]
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: config poetry
        shell: bash
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry config repositories.test "https://test.pypi.org/legacy/"
          poetry config pypi-token.test ${{ secrets.TEST_PYPI_TOKEN }}
      - name: publish test
        shell: bash
        run: poetry publish --build --no-interaction --repository test
      - name: publish
        shell: bash
        run: poetry publish --build --no-interaction
