name: publish
on:
  release:
    types: [published]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test-publish
        uses: JRubics/poetry-publish@v1.11
        with:
          pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"
      - name: publish
        uses: JRubics/poetry-publish@v1.11
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
